services:
  # DHCP and TFTP server (Host networking required for DHCP broadcasts)
  dnsmasq:
    image: strm/dnsmasq:latest
    container_name: opi-netboot-dnsmasq
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./tftp:/var/tftp:ro
    restart: unless-stopped

  # HTTP file server for Talos kernel, initramfs, and cloud-init / machine configs
  http-server:
    image: nginx:alpine
    container_name: opi-netboot-http
    network_mode: host
    volumes:
      - ./http:/usr/share/nginx/html:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
