#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# Script: 03-handoff-uds.sh
# Purpose: Pass provisioned Orange Pi cluster configuration to uds-platform-prep
# ==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
UDS_PREP_DIR="$(cd "${ROOT_DIR}/../uds-platform-prep" 2>/dev/null && pwd || echo "${ROOT_DIR}/../uds-platform-prep")"

# Load configuration
if [[ -f "${ROOT_DIR}/env" ]]; then
    # shellcheck disable=SC1091
    source "${ROOT_DIR}/env"
elif [[ -f "${ROOT_DIR}/env.example" ]]; then
    # shellcheck disable=SC1091
    source "${ROOT_DIR}/env.example"
fi

TARGET_IP="${TARGET_IP:-192.168.42.100}"
KUBECONFIG_PATH="${ROOT_DIR}/kubeconfig"

echo "======================================================================"
echo "Handoff to UDS Platform Prep (uds-platform-prep)"
echo "Target Host: ${TARGET_IP}"
echo "======================================================================"

if [[ ! -d "${UDS_PREP_DIR}" ]]; then
    echo "Notice: uds-platform-prep directory not found at ${UDS_PREP_DIR}."
    echo "For standalone on-device deployment:"
    echo "  1. Boot the Orange Pi with monitor, keyboard, and mouse."
    echo "  2. Open UDS Terminal on the desktop."
    echo "  3. Run: uds deploy <bundle-path>"
    exit 0
fi

echo "[1/2] Creating target.env for Orange Pi in uds-platform-prep..."
cat << EOF > "${UDS_PREP_DIR}/target.env"
# Auto-generated by orangepi-airgapped
TARGET_HOST="${TARGET_IP}"
TARGET_USER="armbian"
DEPLOY_TARGET="k3s"
ARCH="arm64"
EOF

if [[ -f "${KUBECONFIG_PATH}" ]]; then
    echo "[2/2] Linking kubeconfig to uds-platform-prep..."
    cp "${KUBECONFIG_PATH}" "${UDS_PREP_DIR}/kubeconfig"
fi

echo ""
echo "======================================================================"
echo "Handoff Complete!"
echo "Options for deploying UDS:"
echo "1. On-Device (Recommended Standalone Air-Gap):"
echo "   - Power on Orange Pi with monitor and keyboard."
echo "   - Use the pre-installed UDS Terminal or run: uds deploy ..."
echo ""
echo "2. Remote / Tethered via Laptop:"
echo "   - cd ${UDS_PREP_DIR}"
echo "   - make download ARCH=arm64"
echo "   - make deploy"
echo "======================================================================"
