#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# Script: 05-handoff-uds.sh
# Purpose: Pass provisioned Orange Pi cluster to uds-platform-prep for Zarf/UDS
# ==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
UDS_PREP_DIR="$(cd "${ROOT_DIR}/../uds-platform-prep" && pwd)"

# Load configuration
if [[ -f "${ROOT_DIR}/env" ]]; then
    # shellcheck disable=SC1091
    source "${ROOT_DIR}/env"
elif [[ -f "${ROOT_DIR}/env.example" ]]; then
    # shellcheck disable=SC1091
    source "${ROOT_DIR}/env.example"
fi

TARGET_IP="${TARGET_IP:-192.168.42.100}"
KUBECONFIG_PATH="${ROOT_DIR}/kubeconfig"

echo "======================================================================"
echo "Handoff to UDS Platform Prep (uds-platform-prep)"
echo "Target Host: ${TARGET_IP}"
echo "======================================================================"

if [[ ! -f "${KUBECONFIG_PATH}" ]]; then
    echo "Error: ${KUBECONFIG_PATH} not found. Run 'make bootstrap' first."
    exit 1
fi

echo "[1/3] Verifying cluster API readiness..."
export KUBECONFIG="${KUBECONFIG_PATH}"
kubectl get nodes -o wide

if [[ ! -d "${UDS_PREP_DIR}" ]]; then
    echo "Warning: uds-platform-prep directory not found at ${UDS_PREP_DIR}."
    exit 0
fi

echo "[2/3] Linking kubeconfig to uds-platform-prep..."
cp "${KUBECONFIG_PATH}" "${UDS_PREP_DIR}/kubeconfig"

echo "[3/3] Creating target.env for Orange Pi in uds-platform-prep..."
cat << EOF > "${UDS_PREP_DIR}/target.env"
# Auto-generated by orangepi-pxe-provisioner
TARGET_HOST="${TARGET_IP}"
TARGET_USER="root"
DEPLOY_TARGET="talos"
ARCH="arm64"
EOF

echo ""
echo "======================================================================"
echo "Handoff Complete!"
echo "You can now run UDS prep and deploy packages with:"
echo "  cd ${UDS_PREP_DIR}"
echo "  make download ARCH=arm64"
echo "  make deploy"
echo "======================================================================"
